version: "3.7"

services:
  api:
    build: ./api
    environment:
      - CONNECTION_STRING=postgres://admin:admin@db/demo_db
    depends_on:
      - db
    networks:
      - network-backend
      - network-frontend

  webapp:
    build: ./web
    environment:
      - API_URL=http://api:3001/data
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - network-frontend

  db:
    image: postgres:11.2-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: demo_db
    volumes:
      - ./sql_scripts/:/docker-entrypoint-initdb.d
      - ./postgres-initdb.sh:/docker-entrypoint-initdb.d/init.sh
    networks:
      - network-backend

networks:
  network-backend:
  network-frontend:
