version: "3.7"

services:
  web:
    build:
      context: ./web
    environment:
      - API_URL=http://api:3001/data
    ports:
      - "3000:3000"
    networks:
      - public-network
    depends_on:
     - api

  api:
    build:
      context: ./api
    environment:
      - CONNECTON_STRING=postgres://user_id:admin@db/postgres_db
    networks:
      - public-network
      - private-network
    depends_on:
     - db

  db:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      # to intialize the sql data
      - ./sql_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432"
    networks:
      - private-network

volumes:
  db-data:

networks:
  public-network:
  private-network: