version: "3.7"

services:
  web:
    build:
      context: ./web
    environment:
      - API_URL=http://api:3001/data
    ports:
      - "80:3000"
    networks:
      - public-network
    depends_on:
     - api

  api:
    build:
      context: ./api
    environment:
      - CONNECTON_STRING=postgres://demo_user:demo_user@db/demo_db
    networks:
      - public-network
      - private-network
    depends_on:
     - db

  db:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_user
      POSTGRES_DB: demo_db
    volumes:
      - ./sql_scripts/:/docker-entrypoint-initdb.d/init.sql
    networks:
      - private-network

volumes:
  db-data:

networks:
  public-network:
  private-network: