version: "3.7"

services:
  web:
    build:
      context: ./web
    environment:
      - API_URL=http://api:3001/data
    ports:
      - "80:3000"
    networks:
      - public-network
    depends_on:
     - api

  api:
    build:
      context: ./api
    environment:
      - CONNECTON_STRING=postgres://postgres:postgres@db/postgres
    networks:
      - public-network
      - private-network
    depends_on:
     - db

  db:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./init_sql_scripts/:/docker-entrypoint-initdb.d
    networks:
      - private-network

volumes:
  db-data:

networks:
  public-network:
  private-network: