version: "3.9"

services:
  web:
    build:
      context: ./web
    command: node index.js
    volumes:
     - ./web:/app
    ports:
      - "80:3000"
    networks:
      - public-network
    depends_on:
     - db

  api:
    build:
      context: ./api
    command: node index.js
    networks:
      - public-network
      - private-network
    depends_on:
     - db

  db:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      # to intialize the sql data
      - db-data:./sql_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - /docker-entrypoint-initdb.d/init.sql:/sql_scripts/init.sql
    ports:
      - "5432"
    networks:
      - private-network

volumes:
  db-data:

networks:
  public-network:
  private-network: